export type Biome = 'cove' | 'mist' | 'reef' | 'lantern' | 'star' | 'marsh' | 'cliff' | 'pine' | 'ice' | 'volcanic';

export interface HarborDefinition {
  name: string; subtitle: string; color: string; icon: string;
  reputation: number; capacity: number; requiredBoat: number | null;
  biome: Biome; bend: number; frequency: number; phase: number;
  cargo: readonly [string, string, string, string, string];
}

export const HARBORS: HarborDefinition[] = [
  { name: 'Sleepy Cove', subtitle: 'The gentle beginning', color: '#78cba8', icon: '⌂', reputation: 0, capacity: 0, requiredBoat: null, biome: 'cove', bend: 1.2, frequency: .012, phase: 0, cargo: ['Collector ducks', 'Garden gnomes', 'Inflatable flamingos', 'Antique teapots', 'Mystery boxes'] },
  { name: 'Fogbank Harbour', subtitle: 'Mist and mystery', color: '#a7b9d2', icon: '♜', reputation: 0, capacity: 0, requiredBoat: 1, biome: 'mist', bend: 4.8, frequency: .014, phase: .7, cargo: ['Moon cheese', 'Ice cream', 'Travel gnomes', 'Golden duck', 'Unlabelled crates'] },
  { name: 'Coral Key', subtitle: 'Bright reefs and bold jobs', color: '#f5a481', icon: '✿', reputation: 25, capacity: 22, requiredBoat: null, biome: 'reef', bend: 5.4, frequency: .018, phase: 1.4, cargo: ['Sea glass lamps', 'Festival sails', 'Seahorse tanks', 'Frozen reef treats', 'Sealed reef crates'] },
  { name: 'Lantern Bay', subtitle: 'Night markets on the tide', color: '#dfb57c', icon: '✦', reputation: 70, capacity: 31, requiredBoat: null, biome: 'lantern', bend: 3.9, frequency: .021, phase: 2.3, cargo: ['Paper lanterns', 'Toy automata', 'Velvet costumes', 'Midnight noodles', 'Masked parcels'] },
  { name: 'Starfall Port', subtitle: 'The far end of the old chart', color: '#b3a8df', icon: '★', reputation: 140, capacity: 44, requiredBoat: null, biome: 'star', bend: 6.3, frequency: .013, phase: 2.8, cargo: ['Comet lenses', 'Starfruit baskets', 'Regatta trophies', 'Meteor fragments', 'Cosmic mystery cases'] },
  { name: 'Willowmere', subtitle: 'Reed beds and quiet bends', color: '#9fc88e', icon: '♧', reputation: 170, capacity: 31, requiredBoat: null, biome: 'marsh', bend: 7.1, frequency: .022, phase: .2, cargo: ['Willow baskets', 'Herbal remedies', 'Painted birdhouses', 'Marsh honey', 'Sealed reed chests'] },
  { name: 'Seabird Point', subtitle: 'A windy headland', color: '#9bd0db', icon: '➶', reputation: 205, capacity: 31, requiredBoat: null, biome: 'cliff', bend: 6.1, frequency: .016, phase: 1.7, cargo: ['Birdwatching lenses', 'Kite festival cloth', 'Cliffside cheeses', 'Survey charts', 'Unmarked signal flags'] },
  { name: 'Pinewatch Quay', subtitle: 'A forest meets the tide', color: '#82b99a', icon: '♠', reputation: 240, capacity: 36, requiredBoat: null, biome: 'pine', bend: 5.6, frequency: .026, phase  : .5, cargo: ['Cedar carvings', 'Wild berry jam', 'Pine sap lanterns', 'Wool blankets', 'Locked timber cases'] },
  { name: 'Glasswater Inlet', subtitle: 'A mirrored blue passage', color: '#8ed5d4', icon: '◇', reputation: 275, capacity: 36, requiredBoat: null, biome: 'ice', bend: 2.5, frequency: .028, phase: 1.1, cargo: ['Crystal ornaments', 'Glass buoys', 'Silver mirrors', 'Chilled sorbet', 'Prismatic cases'] },
  { name: 'Emberhook', subtitle: 'Warm rock and red sand', color: '#e8977c', icon: '◆', reputation: 310, capacity: 36, requiredBoat: null, biome: 'volcanic', bend: 6.8, frequency: .019, phase: 2.7, cargo: ['Obsidian bowls', 'Spiced pepper jars', 'Forge tools', 'Hot spring salts', 'Charcoal lockboxes'] },
  { name: 'Tidepool Terrace', subtitle: 'A maze of shallow pools', color: '#8bd0ba', icon: '✿', reputation: 345, capacity: 44, requiredBoat: null, biome: 'reef', bend: 7.4, frequency: .025, phase: .9, cargo: ['Shell mosaics', 'Tidal science kits', 'Coral parasols', 'Seaweed crackers', 'Pearl vaults'] },
  { name: 'Copperbell Wharf', subtitle: 'Bells above the water', color: '#d7b58d', icon: '♬', reputation: 380, capacity: 44, requiredBoat: null, biome: 'lantern', bend: 3.1, frequency: .017, phase: 1.9, cargo: ['Copper bells', 'Clock faces', 'Brass telescopes', 'Cinnamon buns', 'Locked music boxes'] },
  { name: 'Mossy Narrows', subtitle: 'A green and winding cut', color: '#86be8c', icon: '♣', reputation: 415, capacity: 44, requiredBoat: null, biome: 'marsh', bend: 8.2, frequency: .024, phase: 2.5, cargo: ['Moss terrariums', 'Frog figurines', 'Fern seedlings', 'River mint', 'Camouflaged packages'] },
  { name: 'Pearlspire', subtitle: 'White towers by the reef', color: '#d5c5e3', icon: '♜', reputation: 450, capacity: 44, requiredBoat: null, biome: 'reef', bend: 5.9, frequency: .029, phase: .3, cargo: ['Pearl chandeliers', 'Carved shells', 'Festival banners', 'Sea silk scarves', 'Royal pearl cases'] },
  { name: 'Duskfen Landing', subtitle: 'Purple reeds at sunset', color: '#ad9fc4', icon: '☽', reputation: 485, capacity: 44, requiredBoat: null, biome: 'mist', bend: 8.6, frequency: .021, phase: 1.4, cargo: ['Violet dyes', 'Fog lamps', 'Reed paper', 'Night tea', 'Mistbound trunks'] },
  { name: 'Bluecap Sound', subtitle: 'Open water and hard wind', color: '#87b9dc', icon: '≈', reputation: 520, capacity: 50, requiredBoat: null, biome: 'cliff', bend: 4.4, frequency: .014, phase: 2.9, cargo: ['Sailing medals', 'Blue wool coats', 'Wave gauges', 'Saltwater taffy', 'Sealed captain logs'] },
  { name: 'Frostfern Dock', subtitle: 'Ice among evergreen shores', color: '#b9d9d5', icon: '❄', reputation: 555, capacity: 50, requiredBoat: null, biome: 'ice', bend: 7.5, frequency: .019, phase: .8, cargo: ['Frosted glass', 'Pine garlands', 'Snowberry pies', 'Ice carvings', 'Frozen specimen crates'] },
  { name: 'Saffron Steps', subtitle: 'Terraces of warm stone', color: '#e0b67d', icon: '▣', reputation: 590, capacity: 50, requiredBoat: null, biome: 'volcanic', bend: 5.2, frequency: .027, phase: 1.6, cargo: ['Saffron spice', 'Painted tiles', 'Stone planters', 'Sun bread', 'Ceramic strongboxes'] },
  { name: 'Moonmoth Pier', subtitle: 'Lamps in a silver forest', color: '#b7b4df', icon: '✦', reputation: 625, capacity: 50, requiredBoat: null, biome: 'pine', bend: 7.8, frequency: .023, phase: 2.2, cargo: ['Moonmoth silk', 'Silver lanterns', 'Forest clocks', 'Glowberry tonic', 'Midnight parcels'] },
  { name: 'Gullwing Reach', subtitle: 'The long bright cliffs', color: '#a8c9c5', icon: '➶', reputation: 660, capacity: 50, requiredBoat: null, biome: 'cliff', bend: 6.7, frequency: .018, phase: .4, cargo: ['Feather quills', 'Coastal maps', 'Chalk sculptures', 'Picnic hampers', 'Signal tower parts'] },
  { name: 'Firefly Lagoon', subtitle: 'Light dances over reeds', color: '#a7d7a2', icon: '✧', reputation: 695, capacity: 50, requiredBoat: null, biome: 'marsh', bend: 9.1, frequency: .025, phase: 1.2, cargo: ['Firefly jars', 'Lantern lilies', 'Glow paint', 'Lagoon fruit', 'Secret garden boxes'] },
  { name: 'Opalbreaker', subtitle: 'Gems beneath rough surf', color: '#a3c7e1', icon: '◇', reputation: 730, capacity: 50, requiredBoat: null, biome: 'reef', bend: 6.5, frequency: .031, phase: 2.6, cargo: ['Opal pendants', 'Diving helmets', 'Reef sculptures', 'Salted sweets', 'Gemstone safes'] },
  { name: 'Cloudglass Haven', subtitle: 'Pale towers in the mist', color: '#c1d3dd', icon: '♜', reputation: 765, capacity: 50, requiredBoat: null, biome: 'mist', bend: 4.9, frequency: .02, phase: .6, cargo: ['Cloudglass panes', 'Weather vanes', 'Sky kites', 'Warm cocoa', 'Hidden observatory cases'] },
  { name: 'Aurora Shelf', subtitle: 'The northern glowing coast', color: '#99d6c9', icon: '❄', reputation: 800, capacity: 50, requiredBoat: null, biome: 'ice', bend: 8.4, frequency: .022, phase: 1.8, cargo: ['Aurora prisms', 'Frost lanterns', 'Northern textiles', 'Iceberry cordial', 'Celestial archives'] },
  { name: 'Sunrise Crown', subtitle: 'The last cape and a new dawn', color: '#efbf89', icon: '☀', reputation: 835, capacity: 50, requiredBoat: null, biome: 'star', bend: 9.7, frequency: .027, phase: 2.4, cargo: ['Sunrise banners', 'Golden sextants', 'Dawn festival cakes', 'Crown jewels', 'Uncharted treasure'] },
];
